
export const metadata = {
  title: "Accunox_task",
  description: "Generated by create next app",
};

import { Provider } from "react-redux";
import "./globals.css";
import { store } from "./store/store";
import { Providers } from "./store/providers";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Providers >

        {children}
        </Providers>
        </body>
    </html>
  );
}
